server:
  port: 8082
spring:
  application:
    name: service-1
  security:
    user:
      name: client
      password: 123456
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:123456@localhost:8081/eureka/eureka

